---
- name: Install and configure HTTPD
  hosts: web
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state:  latest
    - name:  enable Htppd
      service:
        name: httpd
        state:  started
        enabled:  true
...
